{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <tjxg3_agit.TJXG3Agit object at 0x7f8828630fa0>\n\n    @pytest.mark.asyncio\n    @pytest.mark.run(order=1)\n    @allure.title('test_01')\n    async def test_01(self):\n        await set_agit_sp(10)\n        await set_agit_sp_source('Fixed')\n        await asyncio.sleep(2)\n        pv1 = await get_agit_pv()\n        if pv1 > 0:\n            await set_agit_sp_source('Disable')\n            await asyncio.sleep(2)\n            pv2 = await get_agit_pv()\n            if math.fabs(pv2) > 1e-10:\n                allure.attach(body=f'curr pv is {pv2}, expect is zero', name='Error', attachment_type=allure.attachment_type.TEXT)\n                assert False\n        else:\n            allure.attach(body=f'curr pv is {pv1}, expect is greater than zero', name='Error', attachment_type=allure.attachment_type.TEXT)\n>           assert False\nE           assert False\n\ntests/G3/tjxg3_agit.py:38: AssertionError"}, "attachments": [{"name": "Error", "source": "2c03a289-de0f-4d20-8f8d-2a995fad80f7-attachment.txt", "type": "text/plain"}], "start": 1752828167095, "stop": 1752828175103, "uuid": "07487973-6625-4d7c-ba8c-9be969a14ad4", "historyId": "f26221d393fcfe4ba894b02d2f9e7484", "testCaseId": "f26221d393fcfe4ba894b02d2f9e7484", "fullName": "tests.G3.tjxg3_agit.TJXG3Agit#test_01", "labels": [{"name": "feature", "value": "Agit"}, {"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "Agit"}, {"name": "parentSuite", "value": "tests.G3"}, {"name": "suite", "value": "tjxg3_agit"}, {"name": "subSuite", "value": "TJXG3Agit"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "152350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.G3.tjxg3_agit"}]}