{"name": "test_01", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <tjxg3_do.TJXG3DO object at 0x7f8828645d60>\n\n    @pytest.mark.asyncio\n    @pytest.mark.run(order=1)\n    @allure.title('test_01')\n    async def test_01(self):\n        await set_do_sp(10)\n        await set_do_sp_source('Fixed')\n        await asyncio.sleep(2)\n        pv1 = await get_do_pv()\n        if pv1 > 0:\n            await set_do_sp_source('Disable')\n            await asyncio.sleep(2)\n            pv2 = await get_do_pv()\n            if math.fabs(pv2) > 1e-10:\n                allure.attach(body=f'curr pv is {pv2}, expect is zero', name='Error', attachment_type=allure.attachment_type.TEXT)\n                assert False\n        else:\n            allure.attach(body=f'curr pv is {pv1}, expect is greater than zero', name='Error', attachment_type=allure.attachment_type.TEXT)\n>           assert False\nE           assert False\n\ntests/G3/tjxg3_do.py:38: AssertionError"}, "attachments": [{"name": "Error", "source": "13c8b13b-37fa-46c7-aeb5-bf34d61b7cf5-attachment.txt", "type": "text/plain"}], "start": 1752828175177, "stop": 1752828183186, "uuid": "a0bf7ca6-816d-4fbf-87e8-c278a1cfb572", "historyId": "38f62f891ed3983ec3ce4e9499bda746", "testCaseId": "38f62f891ed3983ec3ce4e9499bda746", "fullName": "tests.G3.tjxg3_do.TJXG3DO#test_01", "labels": [{"name": "feature", "value": "DO"}, {"name": "tag", "value": "asyncio"}, {"name": "tag", "value": "DO"}, {"name": "parentSuite", "value": "tests.G3"}, {"name": "suite", "value": "tjxg3_do"}, {"name": "subSuite", "value": "TJXG3DO"}, {"name": "host", "value": "ubuntu"}, {"name": "thread", "value": "152350-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.G3.tjxg3_do"}]}